version: '3.7'

services:
  jupyter-dev:
    image: jupyter-dev:latest
    container_name: jupyter-dev
    hostname: jupyter-dev
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONHASHSEED=537
    ports:
      - '8888:8888'
    volumes:
      - type: bind
        source: ./regis-msds-jupyter/.jupyter
        target: /home/jovyan/.jupyter

      # MSDS 680 - Machine Learning (2022 Spring 8wk 1)
      - type: bind
        source: ./regis-msds-684-reinforcement-learning
        target: /home/jovyan/work

      # MSDS 650 - Data Analytics (2021 Fall 8wk 2)
      # - type: bind
      #   source: ./regis-msds-650-data-analytics
      #   target: /home/jovyan/work

      # MSDS 610 - Data Engineering (2021 Fall 8wk 1)
      # - type: bind
      #   source: ./regis-msds-610-data-engineering/src
      #   target: /home/jovyan/work

  mongo:
    image: mongo:5.0.2-focal
    container_name: mongodb
    volumes:
      - type: volume
        source: mongo
        target: /data/db

  hadoop:
    image: hadoop-dev:latest
    container_name: hadoop
    volumes:
      - type: volume
        source: hadoop-dfs
        target: /var/hadoop

      - type: bind
        source: ./data
        target: /var/data

      - type: bind
        source: ./hadoop-single-node-cluster/docker-context/hadoop/core-site.xml
        target: /opt/hadoop/etc/hadoop/core-site.xml

      - type: bind
        source: ./hadoop-single-node-cluster/docker-context/hadoop/hdfs-site.xml
        target: /opt/hadoop/etc/hadoop/hdfs-site.xml

      - type: bind
        source: ./hadoop-single-node-cluster/docker-context/hadoop/yarn-site.xml
        target: /opt/hadoop/etc/hadoop/yarn-site.xml

      - type: bind
        source: ./hadoop-single-node-cluster/docker-context/docker-entrypoint.sh
        target: /usr/bin/docker-entrypoint.sh

    ports:
      - '9000:9000' # hdfs://
      - '9870:9870' # http://

  spark-master:
    image: my-bitnami-docker-spark:python-3.9
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONHASHSEED=537
    ports:
      - '8080:8080'

  spark-worker-1:
    image: my-bitnami-docker-spark:python-3.9
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONHASHSEED=537

  spark-worker-2:
    image: my-bitnami-docker-spark:python-3.9
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONHASHSEED=537

volumes:
  mongo:
  hadoop-dfs:

